name: 'Sync Repo to gitcode'
description: 'Sync Repository to gitcode'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  github-repo:
    description: 'GitHub 代码仓库的 SSH URL'
    required: true
    default: ''
  gitcode-repo:
    description: 'gitcode 代码仓库的 SSH URL'
    required: true
    default: ''
  wgetsh:
    description: '下载sh'
    required: False
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-repo }}
    - ${{ inputs.gitcode-repo }}
    - ${{ inputs.wgetsh }}
