name: Sync Repo to GITCODE
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Repo to GITCODE
      uses: juzhijian/sync-repo-to-gitcode@master
      env:
          # 在 GitHub Settings->Secrets 配置 GITCODE_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITCODE_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "git@github.com:serverlesslife-cn/sync-repo-to-gitcode.git"
          # 注意替换为你的 GITCODE 目标仓库地址
          gitcode-repo: "git@e.gitcode.net:donghui1/serverlesslife/sync-repo-to-gitcode.git"
          # 提交前运行sh
          wgetsh: "https://raw.githubusercontent.com/juzhijian/UnraidAPP/main/AppFeed/main.sh"